name: DataViz
channels:
  - conda-forge
  - defaults
dependencies:
  - affine
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - basemap
  - bleach
  - blosc
  - boost-cpp
  - bqplot
  - branca
  - brotlipy
  - bzip2
  - c-blosc2
  - ca-certificates
  - cached-property
  - cached_property
  - cairo
  - cartopy
  - certifi
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - colorama
  - contextily
  - cryptography
  - curl
  - cycler
  - cytoolz
  - dask-core
  - debugpy
  - decorator
  - defusedxml
  - descartes
  - entrypoints
  - et_xmlfile
  - expat
  - ffmpeg
  - fiona
  - flit-core
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - freexl
  - fsspec
  - gdal
  - geographiclib
  - geopandas
  - geopandas-base
  - geopy
  - geos
  - geotiff
  - gettext
  - giflib
  - h5py
  - hdf4
  - hdf5
  - icu
  - idna
  - imagecodecs
  - imageio
  - importlib-metadata
  - importlib_resources
  - intel-openmp
  - ipydatawidgets
  - ipykernel
  - ipyleaflet
  - ipython
  - ipython_genutils
  - ipyvolume
  - ipywebrtc
  - ipywidgets
  - jbig
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - jxrlib
  - kealib
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libaec
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libcurl
  - libdeflate
  - libffi
  - libgdal
  - libglib
  - libiconv
  - libkml
  - liblapack
  - libnetcdf
  - libpng
  - libpq
  - librttopo
  - libsodium
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libwebp-base
  - libxml2
  - libzip
  - libzlib
  - libzopfli
  - locket
  - lz4-c
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - mapclassify
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mercantile
  - mistune
  - mkl
  - more-itertools
  - mpmath
  - msys2-conda-epoch
  - munch
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - nest-asyncio
  - networkx
  - nltk
  - notebook
  - numpy
  - olefile
  - openjpeg
  - openpyxl
  - openssl
  - packaging
  - palettable
  - pandas
  - pandoc
  - pandocfilters
  - parso
  - partd
  - pcre
  - pickleshare
  - pillow
  - pip
  - pixman
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - pyrsistent
  - pyshp
  - pysocks
  - python
  - python-dateutil
  - python_abi
  - pythreejs
  - pytz
  - pywavelets
  - pywin32
  - pywinpty
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - qtconsole-base
  - qtpy
  - rasterio
  - regex
  - requests
  - rtree
  - scikit-image
  - scikit-learn
  - scipy
  - send2trash
  - setuptools
  - shapely
  - six
  - snappy
  - sniffio
  - snuggs
  - sqlite
  - sympy
  - tbb
  - terminado
  - testpath
  - threadpoolctl
  - tifffile
  - tiledb
  - tk
  - toml
  - toolz
  - tornado
  - tqdm
  - traitlets
  - traittypes
  - typing_extensions
  - ucrt
  - unyt
  - urllib3
  - vc
  - vs2015_runtime
  - wcwidth
  - webcolors
  - webencodings
  - wheel
  - widgetsnbextension
  - win_inet_pton
  - winpty
  - wordcloud
  - xerces-c
  - xlrd
  - xyzservices
  - xz
  - yaml
  - yt
  - zeromq
  - zfp
  - zipp
  - zlib
  - zstd
